#!/bin/bash

echo "Mounting external HDD..."
echo "==========================="
mount UUID=2017-F074 /mnt 
echo "Unencrypting..."
cryptsetup luksOpen --key-file $(cat ~/.tmpkey) /dev/disk/by-uuid/$(cat ~/.tmpdevice) Sapporo 
umount /mnt
echo "Mounting..."
mount /dev/mapper/Sapporo /data
echo "==========================="



